
pipelines:
  - name: multibranch2
    steps:
      - name: multibranch2_1
        type: Bash
        configuration:
          inputResources:
            - name: multibranch2
              trigger: false
        execution:
          onExecute:
            - echo $step_url

      - name: multibranch2_2
        type: Bash
        configuration:
          inputSteps:
            - name: multibranch2_1
          inputResources:
            - name: multibranch2
        execution:
          onStart:
            - echo "Prepping build environment"
          onExecute:
            - update_commit_status multibranch2
