resources:
  - name: multibranch1
    type: GitRepo
    configuration:
      gitProvider: aidan_github
      path: a-murphy/5testRename5
  - name: multibranchProperties
    type: PropertyBag
    configuration:
      branch: {{gitBranch}}
 
pipelines:
  - name: multibranch1
    steps:
      - name: multibranch1_1
        type: Bash
        configuration:
          inputResources:
            - name: multibranch1
              trigger: false
        execution:
          onExecute:
            - echo $step_url

      - name: multibranch1_2
        type: Bash
        configuration:
          inputSteps:
            - name: multibranch1_1
          inputResources:
            - name: multibranch1
        execution:
          onStart:
            - echo "Prepping build environment"
          onExecute:
            - update_commit_status multibranch1
