resources:
  - name: multibranch2
    type: GitRepo
    configuration:
      gitProvider: aidan_github
      path: a-murphy/test-multibranch
  - name: multibranchProperties
    type: PropertyBag
    configuration:
      branch: {{gitBranch}}
 
pipelines:
  - name: multibranch2
    steps:
      - name: multibranch2_1
        type: Bash
        configuration:
          inputResources:
            - name: multibranch2
              trigger: false
              branch: "multibranch/two"
            - name: gitRepoResource
          outputResources:
            - name: multibranchProperties
              branch: master
        execution:
          onExecute:
            - echo $step_url
            - write_output multibranchProperties test=$run_number

      - name: multibranch2_2
        type: Bash
        configuration:
          inputSteps:
            - name: multibranch2_1
          inputResources:
            - name: multibranch1
              branch: master
            - name: multibranch2
              trigger: false
              branch: "multibranch/three"
        execution:
          onStart:
            - echo "Prepping build environment"
          onExecute:
            - update_commit_status multibranch2
